import os
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm, inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def generate_pdf_report(scan_id: str, timestamp: str, compliance_report: dict, image_path: str, output_path: str):
    """
    Generates a PDF compliance inspection report using ReportLab.
    """
    # Create the directory if it doesn't exist
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    # 20mm top/bottom, 15mm left/right
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=15*mm,
        leftMargin=15*mm,
        topMargin=20*mm,
        bottomMargin=20*mm
    )
    
    elements = []
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        name='TitleStyle',
        parent=styles['Heading1'],
        fontSize=18,
        textColor=colors.HexColor('#1a1a2e'),
        alignment=1,
        spaceAfter=20
    )
    
    elements.append(Paragraph('NIRIKSHAN — Compliance Inspection Report', title_style))
    
    # Scan Info Table
    info_data = [
        ['Scan ID', scan_id],
        ['Timestamp', timestamp],
        ['Overall Status', compliance_report.get('overall_status', 'UNKNOWN')],
        ['Rules Checked', str(compliance_report.get('total_rules_checked', 0))],
        ['Rules Passed', str(compliance_report.get('rules_passed', 0))],
        ['Rules Failed', str(compliance_report.get('rules_failed', 0))]
    ]
    
    info_table = Table(info_data, colWidths=[2*inch, 4*inch])
    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey)
    ]))
    
    elements.append(info_table)
    elements.append(Spacer(1, 20))
    
    # Rule-wise Results Table
    rule_data = [['Rule ID', 'Rule Name', 'Section', 'Status']]
    
    for rule in compliance_report.get('rule_results', []):
        rule_data.append([
            rule.get('rule_id', ''),
            rule.get('rule_name', ''),
            rule.get('section', ''),
            rule.get('status', '')
        ])
        
    rule_table = Table(rule_data, colWidths=[1*inch, 3*inch, 1.5*inch, 1*inch])
    
    table_style = TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#16213e')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey)
    ])
    
    # Add colors for PASS/FAIL
    for i, row in enumerate(rule_data[1:], start=1):
        status = row[3]
        if status == 'PASS':
            table_style.add('TEXTCOLOR', (3, i), (3, i), colors.green)
        elif status == 'FAIL':
            table_style.add('TEXTCOLOR', (3, i), (3, i), colors.red)
            
    rule_table.setStyle(table_style)
    elements.append(rule_table)
    elements.append(Spacer(1, 20))
    
    # Violations List
    violations = compliance_report.get('violations', [])
    font_violations = compliance_report.get('font_violations', [])
    
    if violations or font_violations:
        elements.append(Paragraph('Violations:', styles['Heading2']))
        
        for v in violations:
            elements.append(Paragraph(f"• {v.get('rule_id')}: {v.get('rule_name')} - {v.get('description')}", styles['Normal']))
            
        for fv in font_violations:
            elements.append(Paragraph(f"• Font Violation: '{fv.get('text')}' (Size: {fv.get('font_size_mm'):.2f}mm, Required: {fv.get('min_required_mm')}mm)", styles['Normal']))
            
        elements.append(Spacer(1, 20))
        
    # Photo Evidence
    if os.path.exists(image_path):
        elements.append(Paragraph('Photo Evidence:', styles['Heading2']))
        try:
            img = Image(image_path, width=4*inch, height=3*inch)
            elements.append(img)
        except Exception:
            elements.append(Paragraph('(Image could not be loaded)', styles['Normal']))
            
    elements.append(Spacer(1, 40))
    
    # Footer
    elements.append(Paragraph('Generated by Nirikshan', styles['Italic']))
    elements.append(Paragraph('Reference: Legal Metrology (Packaged Commodities) Rules, 2011', styles['Italic']))
    
    doc.build(elements)
